//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileArchiver.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileArchiver.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during adding of files to the archive.
        ///Details: {0}.
        /// </summary>
        public static string AddFilesError {
            get {
                return ResourceManager.GetString("AddFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive format.
        /// </summary>
        public static string ArchiveFormat {
            get {
                return ResourceManager.GetString("ArchiveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive settings.
        /// </summary>
        public static string ArchiveSettings {
            get {
                return ResourceManager.GetString("ArchiveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path.
        /// </summary>
        public static string DestinationPath {
            get {
                return ResourceManager.GetString("DestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting {0}. Please wait....
        /// </summary>
        public static string ExtractEntireArchiveProgressForm_Description {
            get {
                return ResourceManager.GetString("ExtractEntireArchiveProgressForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the extraction.
        ///Details: {0}.
        /// </summary>
        public static string ExtractError {
            get {
                return ResourceManager.GetString("ExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the directory to extract selected files to....
        /// </summary>
        public static string ExtractFileBrowseDirectoryDescription {
            get {
                return ResourceManager.GetString("ExtractFileBrowseDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting. Please wait....
        /// </summary>
        public static string ExtractProgressForm_Description {
            get {
                return ResourceManager.GetString("ExtractProgressForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting.
        /// </summary>
        public static string ExtractProgressForm_Title {
            get {
                return ResourceManager.GetString("ExtractProgressForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files in current directory: {0}.
        /// </summary>
        public static string FilesInDirectoryStatusText {
            get {
                return ResourceManager.GetString("FilesInDirectoryStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-zip archive.
        /// </summary>
        public static string Filter_7zip {
            get {
                return ResourceManager.GetString("Filter_7zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string Filter_AllFiles {
            get {
                return ResourceManager.GetString("Filter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported archives.
        /// </summary>
        public static string Filter_SupportedArchives {
            get {
                return ResourceManager.GetString("Filter_SupportedArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tar archive.
        /// </summary>
        public static string Filter_tar {
            get {
                return ResourceManager.GetString("Filter_tar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tar archive with GZip compression.
        /// </summary>
        public static string Filter_tar_gz {
            get {
                return ResourceManager.GetString("Filter_tar_gz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip archive.
        /// </summary>
        public static string Filter_zip {
            get {
                return ResourceManager.GetString("Filter_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Add {
            get {
                object obj = ResourceManager.GetObject("Icon_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Directory {
            get {
                object obj = ResourceManager.GetObject("Icon_Directory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Extract {
            get {
                object obj = ResourceManager.GetObject("Icon_Extract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_File {
            get {
                object obj = ResourceManager.GetObject("Icon_File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_MoveUp {
            get {
                object obj = ResourceManager.GetObject("Icon_MoveUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_New {
            get {
                object obj = ResourceManager.GetObject("Icon_New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Open {
            get {
                object obj = ResourceManager.GetObject("Icon_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Remove {
            get {
                object obj = ResourceManager.GetObject("Icon_Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icon_Save {
            get {
                object obj = ResourceManager.GetObject("Icon_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is invalid!.
        /// </summary>
        public static string InvalidNameValidationError {
            get {
                return ResourceManager.GetString("InvalidNameValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File with specified name already exists!.
        /// </summary>
        public static string NameInUseValidationError {
            get {
                return ResourceManager.GetString("NameInUseValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the archive. The format of {0} is unsupported..
        /// </summary>
        public static string NotSupportedFormatError {
            get {
                return ResourceManager.GetString("NotSupportedFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the opening of the archive.
        ///Details: {0}.
        /// </summary>
        public static string OpenError {
            get {
                return ResourceManager.GetString("OpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening. Please wait....
        /// </summary>
        public static string OpenProgressForm_Description {
            get {
                return ResourceManager.GetString("OpenProgressForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        public static string OpenProgressForm_Title {
            get {
                return ResourceManager.GetString("OpenProgressForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the packing of the files.
        ///Details: {0}.
        /// </summary>
        public static string PackError {
            get {
                return ResourceManager.GetString("PackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing files into {0}. Please wait....
        /// </summary>
        public static string PackingProgressForm_Description {
            get {
                return ResourceManager.GetString("PackingProgressForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing.
        /// </summary>
        public static string PackingProgressForm_Title {
            get {
                return ResourceManager.GetString("PackingProgressForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes made to {0}?.
        /// </summary>
        public static string SaveChangesQuestion {
            get {
                return ResourceManager.GetString("SaveChangesQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string SaveChangesQuestionTitle {
            get {
                return ResourceManager.GetString("SaveChangesQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the saving of the archive.
        ///Details: {0}.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving. Please wait....
        /// </summary>
        public static string SaveProgressForm_Description {
            get {
                return ResourceManager.GetString("SaveProgressForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string SaveProgressForm_Title {
            get {
                return ResourceManager.GetString("SaveProgressForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving of an archive in this format is unsupported..
        /// </summary>
        public static string SavingUnsupportedError {
            get {
                return ResourceManager.GetString("SavingUnsupportedError", resourceCulture);
            }
        }
    }
}
